import type { MenuConfig } from '@/types/menu.types'

export const menuConfig: MenuConfig = {
  restaurant: {
    id: 'aarti-food',
    name: 'Artis Cafes',
    tagline: 'Quickverse',
    currency: 'INR',
    currencySymbol: '₹',
  },
  categories: [
    {
      id: 'breakfast',
      title: 'Breakfast',
      description: '',
      displayOrder: 1,
      isActive: true,
      items: [
        { id: 'fresh-healthy-poha', name: 'Fresh & Healthy Poha', description: '', image: 'fresh-healthy-poha.jpg', pricing: [{ label: 'Regular', price: 30 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: ['Breakfast'], displayOrder: 1 },
        { id: 'upma', name: 'Upma', description: '', image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 30 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 2 },
        { id: 'sheera', name: 'Sheera', description: '', image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 30 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 3 },
        { id: 'idli-sambhar', name: 'Idli Sambhar', description: '', image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=300&q=80', pricing: [{ label: '2 Pcs', price: 30 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 4 },
      ],
    },
    {
      id: 'maggies',
      title: 'Maggies',
      description: '',
      displayOrder: 2,
      isActive: true,
      items: [
        { id: 'plain-maggi', name: 'Plain Maggi', description: '', image: 'https://images.unsplash.com/photo-1612966608967-3e2b8630ee78?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 40 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'veg-maggi', name: 'Veg Maggi', description: '', image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 50 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 2 },
        { id: 'cheese-maggi', name: 'Cheese Maggi', description: '', image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 3 },
        { id: 'egg-maggi', name: 'Egg Maggi', description: '', image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: false, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 4 },
      ],
    },
    {
      id: 'paratha',
      title: 'Paratha',
      description: '',
      displayOrder: 3,
      isActive: true,
      items: [
        { id: 'aloo-paratha', name: 'Aloo Paratha', description: '', image: 'aloo-paratha-1.jpg', pricing: [{ label: 'Regular', price: 60 }, { label: 'With Butter', price: 70 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'paneer-paratha', name: 'Paneer Paratha', description: '', image: 'paneer-paratha.jpg', pricing: [{ label: 'Regular', price: 70 }, { label: 'With Butter', price: 80 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 2 },
        { id: 'mix-paratha', name: 'Mix Paratha', description: '', image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 70 }, { label: 'With Butter', price: 80 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 3 },
        { id: 'gobi-paratha', name: 'Gobi Paratha', description: '', image: 'gobi-paratha.jpg', pricing: [{ label: 'Regular', price: 60 }, { label: 'With Butter', price: 70 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 4 },
      ],
    },
    {
      id: 'roti',
      title: 'Roti',
      description: '',
      displayOrder: 4,
      isActive: true,
      items: [
        { id: 'plain-roti', name: 'Plain Roti', description: '', image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=300&q=80', pricing: [{ label: '1 Pc', price: 10 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'butter-roti', name: 'Butter Roti', description: '', image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=300&q=80', pricing: [{ label: '1 Pc', price: 15 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 2 },
        { id: 'chapati', name: 'Chapati', description: '', image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=300&q=80', pricing: [{ label: '1 Pc', price: 10 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 3 },
      ],
    },
    {
      id: 'burger',
      title: 'Burger',
      description: '',
      displayOrder: 5,
      isActive: true,
      items: [
        { id: 'veg-burger', name: 'Veg Burger', description: '', image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'aloo-tikki-burger', name: 'Aloo Tikki Burger', description: '', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 70 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 2 },
        { id: 'paneer-burger', name: 'Paneer Burger', description: '', image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 90 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: true, tags: [], displayOrder: 3 },
        { id: 'egg-burger', name: 'Egg Burger', description: '', image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 80 }], isVeg: false, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 4 },
      ],
    },
    {
      id: 'sandwich',
      title: 'Sandwich',
      description: '',
      displayOrder: 6,
      isActive: true,
      items: [
        { id: 'veg-sandwich', name: 'Veg Sandwich', description: '', image: 'https://images.unsplash.com/photo-1540713702213-9875573346d8?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 50 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'corn-sandwich', name: 'Corn Sandwich', description: '', image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 2 },
        { id: 'veg-cheese-grill-sandwich', name: 'Veg Cheese Grill Sandwich', description: '', image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 80 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 3 },
        { id: 'paneer-grill-sandwich', name: 'Paneer Grill Sandwich', description: '', image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 90 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: true, tags: [], displayOrder: 4 },
        { id: 'egg-sandwich', name: 'Egg Sandwich', description: '', image: 'egg-sandwich.jpg', pricing: [{ label: 'Regular', price: 70 }], isVeg: false, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 5 },
      ],
    },
    {
      id: 'cold-beverages',
      title: 'Cold Beverages',
      description: '',
      displayOrder: 7,
      isActive: true,
      items: [
        { id: 'cold-coffee', name: 'Cold Coffee', description: '', image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }, { label: 'Large', price: 80 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'cold-coffee-ice-cream', name: 'Cold Coffee with Ice Cream', description: '', image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 80 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 2 },
        { id: 'mango-shake', name: 'Mango Shake', description: '', image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 70 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: ['Seasonal'], displayOrder: 3 },
        { id: 'banana-shake', name: 'Banana Shake', description: '', image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 4 },
        { id: 'fresh-lime-soda', name: 'Fresh Lime Soda', description: '', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 40 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 5 },
      ],
    },
    {
      id: 'tea-spot',
      title: 'Tea Spot',
      description: '',
      displayOrder: 8,
      isActive: true,
      items: [
        { id: 'cutting-chai', name: 'Cutting Chai', description: '', image: 'cutting-chai.jpg', pricing: [{ label: 'Regular', price: 10 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'special-masala-chai', name: 'Special Masala Chai', description: '', image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 20 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 2 },
        { id: 'ginger-lemon-tea', name: 'Ginger Lemon Tea', description: '', image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 20 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 3 },
        { id: 'green-tea', name: 'Green Tea', description: '', image: 'https://images.unsplash.com/photo-1627435601357-374b1be0b516?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 25 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 4 },
      ],
    },
    {
      id: 'rolls',
      title: 'Rolls',
      description: '',
      displayOrder: 9,
      isActive: true,
      items: [
        { id: 'veg-roll', name: 'Veg Roll', description: '', image: 'https://images.unsplash.com/photo-1626700051175-6518c4793f4f?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 1 },
        { id: 'paneer-roll', name: 'Paneer Roll', description: '', image: 'paneer-roll.jpg', pricing: [{ label: 'Regular', price: 80 }], isVeg: true, isAvailable: true, isPopular: true, isRecommended: false, isNew: false, tags: [], displayOrder: 2 },
        { id: 'egg-roll', name: 'Egg Roll', description: '', image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 70 }], isVeg: false, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: [], displayOrder: 3 },
      ],
    },
    {
      id: 'salad',
      title: 'Salad',
      description: '',
      displayOrder: 10,
      isActive: true,
      items: [
        { id: 'healthy-salad', name: 'Healthy Salad', description: '', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 50 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: [], displayOrder: 1 },
        { id: 'fruit-salad', name: 'Fruit Salad', description: '', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 60 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: ['Seasonal'], displayOrder: 2 },
      ],
    },
    {
      id: 'special-multi-grain',
      title: 'Special Multi Grain',
      description: '',
      displayOrder: 11,
      isActive: true,
      items: [
        { id: 'multigrain-roti', name: 'Multi Grain Roti', description: '', image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=300&q=80', pricing: [{ label: '1 Pc', price: 15 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: false, isNew: false, tags: ['Healthy'], displayOrder: 1 },
        { id: 'multigrain-paratha', name: 'Multi Grain Paratha', description: '', image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 70 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: false, tags: ['Healthy'], displayOrder: 2 },
      ],
    },
    {
      id: 'seasonal-special',
      title: 'Seasonal Special',
      description: '',
      displayOrder: 12,
      isActive: true,
      items: [
        { id: 'seasonal-special-thali', name: 'Seasonal Special Thali', description: '', image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=300&q=80', pricing: [{ label: 'Regular', price: 120 }], isVeg: true, isAvailable: true, isPopular: false, isRecommended: true, isNew: true, tags: ['Seasonal', 'Special'], displayOrder: 1 },
      ],
    },
  ],
}
